### PR TITLE
add generic prometheus plugin

### PR DESCRIPTION
**Pull request by juckerf**
this pull requests adds a generic configurable prometheus plugin to scrape any prometheus exporter endpoint and write its data to new relic.
See Readme.rst for details

### CODE REVIEW

**Comment by wolph** [comment]
Since I've completely stopped using newrelic I can't really test, but it looks really good!

**Comment by Rockstar04** [comment]
While I still use NewRelic, I do not use this plugin myself anymore either. The code does look really nice, so I'll merge it in.

**Comment by juckerf** [comment]
thanks for the merge!
@Rockstar04  do you also consider releasing a new version with recent changes on PyPi?

**Comment by Rockstar04** [comment]
Oh goodness... I will take a look at doing that. I have not pushed a package to PyPi since this was last updated, and I have moved to a new PC since then.

**Comment by Rockstar04** [comment]
Okay that wasn't as bad as I remember it, I think its updated. You can open an new issue ticket if there is a problem with the new version

**Comment by juckerf** [comment]
Thanks a lot! :)

**Pull request merged**
